name: form-builder
services:
  backend:
    image: form-builder/backend:latest
    build:
        context: ../
        dockerfile: FormBuilder.Api/Dockerfile
    container_name: form-builder-backend
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure

  database:
    container_name: form-builder-database
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=form-builder
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
        
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
  db-data: