// <auto-generated />
using System;
using FormBuilder.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormBuilder.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240915170034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormBuilder.Entities.FormStructureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("FormStructureEntity");
                });

            modelBuilder.Entity("FormBuilder.Entities.FormStructureInputEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormStructureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InputId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FormStructureId");

                    b.HasIndex("InputId");

                    b.ToTable("FormStructureInputEntity");
                });

            modelBuilder.Entity("FormBuilder.Entities.InputEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("InputEntity");
                });

            modelBuilder.Entity("FormBuilder.Entities.FormStructureInputEntity", b =>
                {
                    b.HasOne("FormBuilder.Entities.FormStructureEntity", "FormStructure")
                        .WithMany("FormStructureInputs")
                        .HasForeignKey("FormStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormBuilder.Entities.InputEntity", "Input")
                        .WithMany("FormStructureInputs")
                        .HasForeignKey("InputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormStructure");

                    b.Navigation("Input");
                });

            modelBuilder.Entity("FormBuilder.Entities.FormStructureEntity", b =>
                {
                    b.Navigation("FormStructureInputs");
                });

            modelBuilder.Entity("FormBuilder.Entities.InputEntity", b =>
                {
                    b.Navigation("FormStructureInputs");
                });
#pragma warning restore 612, 618
        }
    }
}
