@FormBuilderApi_HostAddress = http://localhost:8080
@Endpoint_FormStructures = /api/form-structures
@Endpoint_Inputs = /api/inputs

### FormStructures: Get
GET {{FormBuilderApi_HostAddress}}{{Endpoint_FormStructures}} HTTP/1.1
Accept: application/json


### FormStructures: Save
POST {{FormBuilderApi_HostAddress}}{{Endpoint_FormStructures}}/inputs HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "FormStructureId": "7b34146f-fae0-46d1-8552-a68b0a45743e",
  "InputId": "32b289c1-00e1-43d5-810c-45a653fe334a"
}


### Inputs: Save
POST {{FormBuilderApi_HostAddress}}{{Endpoint_Inputs}} HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "Name": "Apellidos",
  "DataType": "string",
  "Required": true
}

### Inputs: Get
GET {{FormBuilderApi_HostAddress}}{{Endpoint_Inputs}} HTTP/1.1
Accept: application/json